"""
02_run_statistics.py

Recomputes one-way ANOVA and Tukey HSD post-hoc tests on every
replicate-level dataset generated by 01_generate_datasets.py, and writes
the results to results/. This reproduces the statistical workflow behind
Tables 4, 5, 8, 9, 23, 25, 27 and 29 of the manuscript.

Because the individual specimen values here were synthesized from the
manuscript's own reported mean/SD/n (see 01_generate_datasets.py), the F
and p values below will be close to, but not bit-identical to, the values
printed in the manuscript (which came from the authors' original,
unavailable raw-data file). Differences of a few percent in F are
expected and are a property of the summary-statistics reconstruction, not
an error.
"""

import pandas as pd
import scipy.stats as stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw_mechanical"
ILLUS = ROOT / "data" / "illustrative"
RESULTS = ROOT / "results"
RESULTS.mkdir(exist_ok=True)

GROUP_ORDER = ["0g", "1g", "2g"]


def anova_and_tukey(df, value_col, group_col="nanoclay_loading", label=""):
    groups = [df.loc[df[group_col] == g, value_col].values for g in GROUP_ORDER]
    f, p = stats.f_oneway(*groups)
    dfb = len(groups) - 1
    dfw = len(df) - len(groups)
    tukey = pairwise_tukeyhsd(df[value_col].values, df[group_col].values)
    tukey_df = pd.DataFrame(tukey.summary().data[1:], columns=tukey.summary().data[0])
    tukey_df.insert(0, "property", label)
    anova_row = {
        "property": label, "F": round(f, 2), "df_between": dfb, "df_within": dfw,
        "p_value": f"{p:.3e}",
    }
    return anova_row, tukey_df


def process(csv_path, value_cols, tag):
    df = pd.read_csv(csv_path)
    anova_rows, tukey_frames = [], []
    for col in value_cols:
        row, tdf = anova_and_tukey(df, col, label=col)
        anova_rows.append(row)
        tukey_frames.append(tdf)
    anova_out = pd.DataFrame(anova_rows)
    tukey_out = pd.concat(tukey_frames, ignore_index=True)
    anova_out.to_csv(RESULTS / f"{tag}_ANOVA.csv", index=False)
    tukey_out.to_csv(RESULTS / f"{tag}_TukeyHSD.csv", index=False)
    print(f"\n=== {tag} : one-way ANOVA ===")
    print(anova_out.to_string(index=False))
    return anova_out, tukey_out


# Table 4/5 equivalent — tensile
process(RAW / "table3_tensile_replicates.csv", ["uts_MPa", "modulus_MPa"], "tensile")

# Table 8/9 equivalent — flexural
process(RAW / "table7_flexural_replicates.csv",
        ["flexural_strength_MPa", "flexural_modulus_GPa"], "flexural")

# Table 23 equivalent — modal (illustrative)
process(ILLUS / "table22_modal_2nd_mode_replicates_ILLUSTRATIVE.csv",
        ["second_freq_Hz", "damping_ratio_pct"], "modal_2ndmode_ILLUSTRATIVE")

# Table 25 equivalent — STL by frequency (illustrative), one ANOVA per frequency
stl = pd.read_csv(ILLUS / "table24_STL_vs_frequency_replicates_ILLUSTRATIVE.csv")
rows = []
for f in sorted(stl["frequency_Hz"].unique()):
    sub = stl[stl["frequency_Hz"] == f]
    row, _ = anova_and_tukey(sub, "STL_dB", label=f"{f} Hz")
    rows.append(row)
pd.DataFrame(rows).to_csv(RESULTS / "STL_by_frequency_ANOVA_ILLUSTRATIVE.csv", index=False)
print("\n=== STL by frequency : one-way ANOVA (illustrative) ===")
print(pd.DataFrame(rows).to_string(index=False))

# Table 27 equivalent — flammability (illustrative)
process(ILLUS / "table26_flammability_replicates_ILLUSTRATIVE.csv",
        ["burn_time_s", "burn_length_mm", "burning_rate_mm_per_min"],
        "flammability_ILLUSTRATIVE")

# Table 29 equivalent — screening properties (illustrative)
process(ILLUS / "table28_screening_properties_replicates_ILLUSTRATIVE.csv",
        ["water_abs_24h_pct", "water_abs_48h_pct", "water_abs_168h_pct",
         "impact_strength_kJ_m2", "density_g_cm3", "hardness_shoreD", "oxygen_index_pct"],
        "screening_properties_ILLUSTRATIVE")

print(f"\nAll ANOVA / Tukey HSD result tables written to {RESULTS}/")
